apiVersion: v1
kind: Pod
metadata:
  name: pod-drop-chown-capability
  namespace: default
spec:
  containers:
  - name: my-container
    image: nginx
    securityContext:
      capabilities:
        drop:
        - CHOWN
