apiVersion: v1
kind: Pod
metadata:
  name: nginx-lab
  namespace: default
spec:
  containers:
  - name: nginx-lab
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 9000
      protocol: TCP
