apiVersion: v1
kind: Pod
metadata:
  name: my-hostnetwork-pod
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
