apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-network
  namespace: default
spec:
  hostNetwork: true
  containers:
  - name: main
    image: alpine # you can use nginx too
    command: ["/bin/sleep", "999999"]  # this container will sleep after this time
    ports:
    - containerPort: 80
      hostPort: 80
